name: AUTO-SYNC_MASTER_DEVELOP

on:
  workflow_dispatch:
  
jobs:
  sync-branches:
    runs-on: ubuntu-20.04
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      
      - name: Opening pull request
        run: |
          git checkout master
          git pull
          git checkout develop
          git merge master
        
