name: Sync multiple branches
on:
  workflow_dispatch:
  
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: xmllint
        run: |
          sudo apt-get install libxml2-utils -y
          curl https://finder.io/sitemap.xml > file.xml
          if xmllint --noout file.xml > /dev/null 2>&1; 
          then
            var=green
            echo "$var"
          else
            var=red
            echo "$var"
          fi
